# Generated by Django 4.2.4 on 2023-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_review',
            field=models.IntegerField(null=True),
        ),
    ]
