# Generated by Django 4.2.4 on 2023-09-02 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='avg_review',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='number_of_production',
            new_name='released',
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='URL',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
